### ISSUE TITLE
Requires X11 at installation (although supposedly X11 support has been dropped)

### ISSUE THREAD

**Issue by Petia** [fikovnik/ShiftIt#105]
When starting Shiftit for the first time (e.g. when it installs), it complains that there is no X11 installed on my system (10.8.3) and then refuses to proceed (so installation stops there and I can't run Shiftit). 
I've no intention to install X11, and anyway X11 support is supposedly abandoned. So what is going on?
Same behavior with 1.5 and 1.6 (devt).

**Comment by andrirad** [comment]
The link to the NoX11 build (http://cl.ly/3p071K0S2B0y) does not work anymore. Can you make the build available again?

**Comment by stembrain** [comment]
@andrirad It works for me. I am accessing from United States. I'll proxy it for you at my site [stembrain.com](http://stembrain.com/ShiftIt-1.6-NoX11.zip)


If someone doesn't mind confirming that the MD5 of ShiftIt-1.6-NoX11.zip is cece57496259db7f3ad283c1d24c62ca that would be great because people could trust my proxy.

**Comment by southrop** [comment]
Confirmed that the two files match.
```
  File: ShiftIt-1.6-NoX11-stembrain.zip
CRC-32: 7af50ef8
   MD4: 266401baee469a2f3a48e055e45baf8f
   MD5: cece57496259db7f3ad283c1d24c62ca
 SHA-1: 08f18d6cc61c0a4acf5c7a5376b4990f88978fd8

  File: ShiftIt-1.6-NoX11.zip
CRC-32: 7af50ef8
   MD4: 266401baee469a2f3a48e055e45baf8f
   MD5: cece57496259db7f3ad283c1d24c62ca
 SHA-1: 08f18d6cc61c0a4acf5c7a5376b4990f88978fd8
```

**Comment by andrirad** [comment]
Thank you it worked
